-- MySQL Script generated by MySQL Workbench
-- Fri Sep 25 19:32:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzaPI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzaPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaPI` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `pizzaPI` ;

-- -----------------------------------------------------
-- Table `pizzaPI`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaPI`.`Cliente` (
  `codCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`codCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `pizzaPI`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaPI`.`Endereco` (
  `codEndereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(45) NULL,
  `bairro` VARCHAR(50) NULL,
  `complemento` VARCHAR(100) NULL,
  `codCliente` INT NOT NULL,
  PRIMARY KEY (`codEndereco`),
  CONSTRAINT `fk_Endereco_Cliente1`
    FOREIGN KEY (`codCliente`)
    REFERENCES `pizzaPI`.`Cliente` (`codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_Endereco_Cliente1_idx` ON `pizzaPI`.`Endereco` (`codCliente` ASC) ;


-- -----------------------------------------------------
-- Table `pizzaPI`.`TipoProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaPI`.`TipoProduto` (
  `codTipoProduto` INT NOT NULL AUTO_INCREMENT,
  `descricaoTipo` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`codTipoProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaPI`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaPI`.`Produtos` (
  `codProdutos` INT NOT NULL AUTO_INCREMENT,
  `descricaoProduto` VARCHAR(120) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `codTipoProduto` INT NOT NULL,
  `statusAtivo` BIT(1) NOT NULL,
  PRIMARY KEY (`codProdutos`),
  CONSTRAINT `fk_Produtos_TipoProduto1`
    FOREIGN KEY (`codTipoProduto`)
    REFERENCES `pizzaPI`.`TipoProduto` (`codTipoProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produtos_TipoProduto1_idx` ON `pizzaPI`.`Produtos` (`codTipoProduto` ASC) ;


-- -----------------------------------------------------
-- Table `pizzaPI`.`Cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaPI`.`Cargos` (
  `codCargos` INT NOT NULL AUTO_INCREMENT,
  `descricaoCargos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codCargos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `pizzaPI`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaPI`.`Usuario` (
  `codUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `login` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `codCargos` INT NOT NULL,
  PRIMARY KEY (`codUsuario`),
  CONSTRAINT `fk_Usuario_Cargos1`
    FOREIGN KEY (`codCargos`)
    REFERENCES `pizzaPI`.`Cargos` (`codCargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_Usuario_Cargos1_idx` ON `pizzaPI`.`Usuario` (`codCargos` ASC) ;


-- -----------------------------------------------------
-- Table `pizzaPI`.`StatusPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaPI`.`StatusPedido` (
  `codStatusPedido` INT NOT NULL AUTO_INCREMENT,
  `statusDescricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codStatusPedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `pizzaPI`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaPI`.`Pedido` (
  `codPedido` INT NOT NULL AUTO_INCREMENT,
  `codStatusPedido` INT NOT NULL,
  `codCliente` INT NOT NULL,
  `codUsuarioRegistro` INT NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `valorPedido` DECIMAL(10,2) NOT NULL,
  `codUsuarioEntrega` INT NULL,
  `dataEntrega` DATETIME NULL,
  `codUsuarioExclusao` INT NULL,
  `dataExclusao` DATETIME NULL,
  PRIMARY KEY (`codPedido`),
  CONSTRAINT `fk_Pedido_StatusPedido1`
    FOREIGN KEY (`codStatusPedido`)
    REFERENCES `pizzaPI`.`StatusPedido` (`codStatusPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`codCliente`)
    REFERENCES `pizzaPI`.`Cliente` (`codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Usuario`
    FOREIGN KEY (`codUsuarioRegistro`)
    REFERENCES `pizzaPI`.`Usuario` (`codUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_Pedido_StatusPedido_idx` ON `pizzaPI`.`Pedido` (`codStatusPedido` ASC) ;

CREATE INDEX `fk_Pedido_Cliente_idx` ON `pizzaPI`.`Pedido` (`codCliente` ASC) ;

CREATE INDEX `fk_Pedido_Usuario_idx` ON `pizzaPI`.`Pedido` (`codUsuarioRegistro` ASC) ;


-- -----------------------------------------------------
-- Table `pizzaPI`.`ItensPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaPI`.`ItensPedido` (
  `codPedido` INT NOT NULL,
  `codProdutos` INT NOT NULL,
  `quatidade` INT NOT NULL,
  `valosFinal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`codPedido`, `codProdutos`),
  CONSTRAINT `fk_ItensPedido_Pedido1`
    FOREIGN KEY (`codPedido`)
    REFERENCES `pizzaPI`.`Pedido` (`codPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItensPedido_Produtos1`
    FOREIGN KEY (`codProdutos`)
    REFERENCES `pizzaPI`.`Produtos` (`codProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_Pedido_has_Produtos_Produtos1_idx` ON `pizzaPI`.`ItensPedido` (`codProdutos` ASC) ;

CREATE INDEX `fk_Pedido_has_Produtos_Pedido1_idx` ON `pizzaPI`.`ItensPedido` (`codPedido` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
